// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PashaBankApp.DbContexti;

#nullable disable

namespace PashaBankApp.Migrations
{
    [DbContext(typeof(DbRaisa))]
    [Migration("20231006190033_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PashaBankApp.Models.Address", b =>
                {
                    b.Property<int>("AdreessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdreessID"));

                    b.Property<string>("AddressInfo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AddressType")
                        .HasColumnType("int");

                    b.HasKey("AdreessID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PashaBankApp.Models.Bonus", b =>
                {
                    b.Property<int>("BonusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BonusID"));

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfBonus")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistributorID")
                        .HasColumnType("int");

                    b.HasKey("BonusID");

                    b.HasIndex("DistributorID");

                    b.ToTable("Bonus");
                });

            modelBuilder.Entity("PashaBankApp.Models.ContactInfo", b =>
                {
                    b.Property<int>("ContactInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactInfoID"));

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("contactType")
                        .HasColumnType("int");

                    b.HasKey("ContactInfoID");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("PashaBankApp.Models.Distributor", b =>
                {
                    b.Property<int>("DistributorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributorID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContactinfoID")
                        .HasColumnType("int");

                    b.Property<int?>("CountOffInvetedDistributor")
                        .HasColumnType("int");

                    b.Property<string>("DistributorLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpireOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int>("PersonalInfoID")
                        .HasColumnType("int");

                    b.Property<int?>("Recomendedby")
                        .HasColumnType("int");

                    b.HasKey("DistributorID");

                    b.HasIndex("AddressID")
                        .IsUnique();

                    b.HasIndex("ContactinfoID")
                        .IsUnique();

                    b.HasIndex("PersonalInfoID")
                        .IsUnique();

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("PashaBankApp.Models.DistributorSale", b =>
                {
                    b.Property<int>("DistributorSaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributorSaleID"));

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpireOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("distributorID")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistributorSaleID");

                    b.HasIndex("ProductID");

                    b.HasIndex("distributorID");

                    b.ToTable("DistributorSales");
                });

            modelBuilder.Entity("PashaBankApp.Models.Error", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorId"));

                    b.Property<int>("ErrorType")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeofOccured")
                        .HasColumnType("datetime2");

                    b.HasKey("ErrorId");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("PashaBankApp.Models.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("PashaBankApp.Models.Manager", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("PashaBankApp.Models.ManagerAuthentification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID")
                        .IsUnique();

                    b.ToTable("ManagerAuthentification");
                });

            modelBuilder.Entity("PashaBankApp.Models.ManagerCookies", b =>
                {
                    b.Property<int>("ManagerCookiesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerCookiesID"));

                    b.Property<int>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerCookiesID");

                    b.HasIndex("ManagerID")
                        .IsUnique();

                    b.ToTable("ManagerCookies");
                });

            modelBuilder.Entity("PashaBankApp.Models.PersonalInfo", b =>
                {
                    b.Property<int>("PersonalInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalInfoID"));

                    b.Property<DateTime>("DateofIssue")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DocumentSeria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonalInfoID");

                    b.ToTable("PersonalInfos");
                });

            modelBuilder.Entity("PashaBankApp.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpireOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PashaBankApp.Models.Bonus", b =>
                {
                    b.HasOne("PashaBankApp.Models.Distributor", "distributor")
                        .WithMany("bonus")
                        .HasForeignKey("DistributorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("distributor");
                });

            modelBuilder.Entity("PashaBankApp.Models.Distributor", b =>
                {
                    b.HasOne("PashaBankApp.Models.Address", "address")
                        .WithOne("distributor")
                        .HasForeignKey("PashaBankApp.Models.Distributor", "AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PashaBankApp.Models.ContactInfo", "contactinfo")
                        .WithOne("distributor")
                        .HasForeignKey("PashaBankApp.Models.Distributor", "ContactinfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PashaBankApp.Models.PersonalInfo", "personalinfo")
                        .WithOne("distributor")
                        .HasForeignKey("PashaBankApp.Models.Distributor", "PersonalInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("address");

                    b.Navigation("contactinfo");

                    b.Navigation("personalinfo");
                });

            modelBuilder.Entity("PashaBankApp.Models.DistributorSale", b =>
                {
                    b.HasOne("PashaBankApp.Models.Product", "product")
                        .WithMany("distributorSales")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PashaBankApp.Models.Distributor", "distributor")
                        .WithMany("distributorSales")
                        .HasForeignKey("distributorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("distributor");

                    b.Navigation("product");
                });

            modelBuilder.Entity("PashaBankApp.Models.ManagerAuthentification", b =>
                {
                    b.HasOne("PashaBankApp.Models.Manager", "manager")
                        .WithOne("authManager")
                        .HasForeignKey("PashaBankApp.Models.ManagerAuthentification", "ManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("manager");
                });

            modelBuilder.Entity("PashaBankApp.Models.ManagerCookies", b =>
                {
                    b.HasOne("PashaBankApp.Models.Manager", "manager")
                        .WithOne("managercookies")
                        .HasForeignKey("PashaBankApp.Models.ManagerCookies", "ManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("manager");
                });

            modelBuilder.Entity("PashaBankApp.Models.Address", b =>
                {
                    b.Navigation("distributor")
                        .IsRequired();
                });

            modelBuilder.Entity("PashaBankApp.Models.ContactInfo", b =>
                {
                    b.Navigation("distributor")
                        .IsRequired();
                });

            modelBuilder.Entity("PashaBankApp.Models.Distributor", b =>
                {
                    b.Navigation("bonus");

                    b.Navigation("distributorSales");
                });

            modelBuilder.Entity("PashaBankApp.Models.Manager", b =>
                {
                    b.Navigation("authManager")
                        .IsRequired();

                    b.Navigation("managercookies")
                        .IsRequired();
                });

            modelBuilder.Entity("PashaBankApp.Models.PersonalInfo", b =>
                {
                    b.Navigation("distributor")
                        .IsRequired();
                });

            modelBuilder.Entity("PashaBankApp.Models.Product", b =>
                {
                    b.Navigation("distributorSales");
                });
#pragma warning restore 612, 618
        }
    }
}
